version: '3'
services:
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tasti
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./.database_data:/var/lib/mysql
